#!/bin/bash

set -e

pushd /db-init-scripts

psql -v ON_ERROR_STOP=1 -f before.sql

psql -v ON_ERROR_STOP=1 -f faa.sql 
psql -v ON_ERROR_STOP=1 -f fwa.sql 

pushd area && psql -v ON_ERROR_STOP=1 -f run.sql && popd
